### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#5]
This shows up if I unplug a pin from one gpio to another.
This might only be an issue when unplugging but maybe not?
(node:8681) ExperimentalWarning: The ESM module loader is experimental.
looping /home/pi/wyrdheim-pi/audio/layer1.mp3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write() failed: 0
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:14)
Emitted 'error' event at:
    at onwriteError (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:9)
(node:8693) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerB-rune.mp3
(node:8706) ExperimentalWarning: The ESM module loader is experimental.
looping /home/pi/wyrdheim-pi/audio/layer2.mp3

**Comment by Continuities** [comment]
What are the observed effects? Does the drone stop looping?

**Comment by acarito** [comment]
I can't recall. Now that I have the logic level controller in place handling the voltage I can leave everything as is/plugged in and it doesn't seem to be happening again.
Every time I restart the Arduino is triggers all the things though. that part is frustrating, but I know it's hardware.

**Comment by Continuities** [comment]
It's likely not a problem. The speaker module crashes sometimes when
stopping, which is why I'm running it in a child process. Unless this error
comes alongside incorrect behaviour, I wouldn't worry.

Relevant: https://github.com/TooTallNate/node-speaker/issues/92

**Comment by Continuities** [comment]
Relevant: https://github.com/TooTallNate/node-speaker/issues/92
