### ISSUE TITLE
Error displayed after trigger B ran unprovoked. in feature

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#7]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write() failed: 2316
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:14)
Emitted 'error' event at:
    at onwriteError (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:9)
(node:7976) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerB-rune.mp3
(node:7987) ExperimentalWarning: The ESM module loader is experimental.
looping /home/pi/wyrdheim-pi/audio/layer1.mp3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write() failed: 584
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:14)
Emitted 'error' event at:
    at onwriteError (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:9)
Daisy, Daisy, give me your answer do...
file:///home/pi/wyrdheim-pi/src/main.mjs:36
    OUTPUT.write(1);
    ^

ReferenceError: OUTPUT is not defined
    at num (file:///home/pi/wyrdheim-pi/src/main.mjs:36:5)
    at increment (file:///home/pi/wyrdheim-pi/src/input-counter.mjs:12:7)
    at gpio._listeners.slice.forEach (/home/pi/wyrdheim-pi/node_modules/onoff/onoff.js:135:9)
    at Array.forEach (<anonymous>)
    at pollerEventHandler (/home/pi/wyrdheim-pi/node_modules/onoff/onoff.js:134:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pi@raspberrypi:~/wyrdheim-pi $ (node:7998) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerB-rune.mp3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at Speaker.speaker.on (/home/pi/wyrdheim-pi/src/player.js:32:39)
    at Speaker.emit (events.js:189:13)
    at Speaker._flush (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:259:10)
    at Speaker.emit (events.js:194:15)
    at finishMaybe (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:483:7)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:216:9)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by Continuities** [comment]
So I definitely screwed up a merge (`OUTPUT` should be `output` now), but I don't know about TriggerB running unprovoked? Was there noise on the GPIO line?
