### ISSUE TITLE
TriggerA runs, as planned, error displays but it keeps running

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#8]
might be related to previous issue, but after Trigger A runs, this is displayed

looping /home/pi/wyrdheim-pi/audio/layer0-drone.mp3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write() failed: 3656
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:14)
Emitted 'error' event at:
    at onwriteError (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:9)
(node:8074) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerA-compartment.mp3
(node:8085) ExperimentalWarning: The ESM module loader is experimental.
looping /home/pi/wyrdheim-pi/audio/layer0-drone.mp3

**Comment by Continuities** [comment]
Yeah, that's not a problem. It happens sometimes when stopping/switching the audio. Related to a bug in the speaker module I'm using (https://github.com/TooTallNate/node-speaker/issues/92).

That's why I'm running the player in a separate process. If it crashes when I try to stop it, it doesn't take down the whole program. And it's okay that it crashed, because we want it to stop anyway.
