### ISSUE TITLE
Trigger B Fired without prompt again

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#9]
I had been running it for about 10 minutes and sat down at my desk and Trigger B started, changing the track. The Arduino is off at the moment so not sure how it fired. Can't be any noise at this point, can it?

looping /home/pi/wyrdheim-pi/audio/layer0-drone.mp3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write() failed: 3784
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:14)
Emitted 'error' event at:
    at onwriteError (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at onwrite (/home/pi/wyrdheim-pi/node_modules/speaker/index.js:210:9)
(node:9080) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerA-compartment.mp3
(node:9091) ExperimentalWarning: The ESM module loader is experimental.
playing /home/pi/wyrdheim-pi/audio/triggerB-rune.mp3
(node:9104) ExperimentalWarning: The ESM module loader is experimental.
looping /home/pi/wyrdheim-pi/audio/layer1.mp3

**Comment by Continuities** [comment]
I see both a triggerA and triggerB in there very strange to happen
automatically.

**Comment by acarito** [comment]
Both fired while the Arduino was off.
later when I ran it while it was one it seemed to be okay. I'm going to run it all day today and check again.

**Comment by Continuities** [comment]
Double-checked the code, and it's just not possible for the triggers to go off without a signal on the GPIO line. 99% certain this is an electrical bug. The Arduino being off doesn't mean the line is clean. You might have a grounding issue?
